### ISSUE TITLE
Add "Private" page functionality

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/hugo-module-tnd-seo#6]
Provide users with a front matter key `private: true`

if set, the page's robots index tag would be set to false and no sharing meta tags would be set.

Reference: https://github.com/theNewDynamic/thenewdynamic.com/issues/89

**Comment by regisphilibert** [comment]
We need to take into consideration the environment. It is safe to assume that no everyone will want noindex,nofollow if not running in 'production'.

That brings the question... How can we safely test for 'production'.

Here is what I thought: 
```
{{ $production := eq "production" (getenv "HUGO_ENV") hugo.Environment }}
```

Which returns tru if the first argument equals any of the subsequent arguments. The problem with the above is that it will return true on any branch or pr deploy... 
`getenv "HUGO_ENV"` is the safest for us, but not sure others are using the same to declare their environment.

I'm bringing this up because if we don't this right, a lot of people might endup with index,follow on their non-production environment.
